paths:
  /api/products:
    get:
      summary: Get all products from the database
      tags:
        - Products
      responses:
        "200":
          description: It gets all products successfully
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Product'
              examples:
                example-1:
                  value:
                    - _id: "64a18c43b1246b2f456fa3d9"
                      title: "Overwhelmed"
                      description: "Released by Drumcode Records"
                      price: 4
                      thumbnail: "https://example.com/image1.jpg"
                      code: "E1"
                      stock: 5
                      status: true
                      category: "Techno"
                    - _id: "64a18c53b1246b2f456fa3d8"
                      title: "Euphoria"
                      description: "Latest hit from Afterlife Records"
                      price: 5
                      thumbnail: "https://example.com/image2.jpg"
                      code: "E2"
                      stock: 10
                      status: true
                      category: "House"
        "500":
          description: Internal server error 
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerated by MongoDB
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product thumbnail URL
        code:
          type: string
          description: Unique product code
        stock:
          type: integer
          description: Available stock
        status:
          type: boolean
          description: Availability status
        category:
          type: string
          description: Product category
